name: Build Node.js

on:
  push:
    branches: [ main ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x, 18.x ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm run lint:nofix

      - name: Setup postgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '13'
          postgresql db: 'postgres'
          postgresql user: 'postgres'
          postgresql password: 'postgres'

      - run: npm test
        env:
          IPINFO_TOKEN: ${{ secrets.IPINFO_TOKEN }}
